### ISSUE TITLE
ICS export ma zle datumy (a teda zle dni)

### ISSUE THREAD

**Issue by yoyko** [fmfi-svt/candle#43]
Utorkove eventy zacinaju 12.2., co je piatok (stredajsie 13.2. atd.., nemam zrovna pondelkovy event v rozvrhu).
Prvy utorok tohto semestra je 16.2.

**Comment by mrshu** [comment]
@yoyko Vdaka za report, uz by to malo byt opravene: problem bol v zle nastavenom datume zaciatku semestra.

Ak to uz funguje ako ma, zavrite, prosim, tuto issue.

Vdaka

**Comment by yoyko** [comment]
Hmmm, skusal som teraz a stale to generuje od 11.2. (skusil som vyrobit uplne novy rozvrh s inymi predmetmi).

**Comment by mrshu** [comment]
Ospravedlnujem sa, bolo este treba premazat cache. Skusil som to, uz by to malo generovat dobre ICS.

**Comment by yoyko** [comment]
Vdaka, datumy su uz dobre.
Este mala chybicka je, ze UNTIL je stale 18.2. (asi podla minuleho semestra), takze posledna streda-piatok semestra chybaju.

**Comment by mrshu** [comment]
Ospravedlnujem sa za neskoru odpoved.

Uz by to malo byt v poriadku. Dajte prosim vediet, ak je tam stale nejaky problem. A ak nie, zavrite prosim tuto issue.

Vdaka

**Comment by yoyko** [comment]
Super, uz je to to spravne
