### ISSUE TITLE
ICS export ma zle datumy (leto 2017)

### ISSUE THREAD

**Issue by yoyko** [fmfi-svt/candle#46]
ICS export ma znova zle datumy, podobne ako #43  (rok je 2013 a datumy su posunute o 2 dni), rovnako aj koniec semestra je zle.

(Neda sa to nejak automatizovat, alebo aspon hodit nejaky warning, ked je ocividne zly rok alebo podobne?)

**Comment by mrshu** [comment]
> ICS export ma znova zle datumy, podobne ako #43 (rok je 2013 a datumy su posunute o 2 dni), rovnako aj koniec semestra je zle.

Vdaka za report. Uz by to malo byt opravene.

Ak to mozete potvrdit, zavrite prosim tuto issue.

> (Neda sa to nejak automatizovat, alebo aspon hodit nejaky warning, ked je ocividne zly rok alebo podobne?)

Ze tento problem opakovane nastava je viac menej procesna chyba, kedy bolo nastavenie spravneho zaciatku/konca semestra vynechane z dokumentacie pouzivanej pri deploymente. V buducnosti by sa to uz stat nemalo.

**Comment by yoyko** [comment]
OK, vyzera dobre.
