### ISSUE TITLE
Anketa popup: možnosť "už som hlasoval"

### ISSUE THREAD

**Issue by gardenerik** [fmfi-svt/candle#56]
Defaultne sa popup schová na 2 dni, čo je veľmi otravné, ak som už v ankete hlasoval. Bolo by fajn pridať button "Už som hlasoval", ktorý by popup schoval dlhodobo.

**Comment by Adman** [comment]
@gardenerik Vdaka za napad. Suhlasim, pri takomto buttone by stacilo nastavit expirovanie toho cookie na hodnotu `anketaCookieHideDate`, po ktorom sa to uz automaticky nezobrazuje. Rovnaky button by sa hodil aj do Votr-u.
Momentalne je v SVT 0 aktivnych clenov, cize ak by si mal zaujem, kludne to mozes fixnut a ja by som to reviewol.
